<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\db\ActiveRecord;

/**
 * LoginForm is the model behind the login form.
 *
 * @property User|null $user This property is read-only.
 *
 */
class Blog extends ActiveRecord
{
    public static function tableName()
    {
        return 'posts'; // TODO: Change the autogenerated stub
    }

    public function getPosts(){

    }
    public function getPost($id_post){

    }
}